[tool.poetry]
name = "pkuphysu-wechat"
version = "0.1.0"
description = ""
authors = ["Allan Chain "]

[tool.poetry.dependencies]
python = ">=3.9,<3.12"
WeRoBot = "^1.13.1"
Flask = "^3.1.0"
command4bot = "^0.4.1"
dynaconf = "^3.2.6"
sqlalchemy = "^2.0.36"
PyMySQL = { version = "^1.1.1", extras = ["rsa"] }
cryptography = "^43.0.3"
flask-sqlalchemy = "^3.1.1"
flask-cors = "^5.0.0"
requests = "^2.32.3"
alembic = "^1.14.0"
Werkzeug = "^3.1.3"

[tool.poetry.group.dev.dependencies]
black = "^24.10.0"
pytest = "^8.3.4"
pre-commit = "^3.8.0"
flake8 = "^7.1.1"
python-dotenv = "^1.0.1"
pylint = "^3.3.1"
coverage = "^7.6.4"
bandit = "^1.7.10"
isort = { version = "^5.13.2", extras = ["colors"] }

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.pytest.ini_options]
addopts = "-v"
log_level = "INFO"
markers = """
    incremental: Incremental Test
"""

[tool.isort]
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
line_length = 88

[tool.pylint.messages_control]
confidence = "HIGH"
disable = "C0114, C0115, C0116, R1705, W0601, W0702, W0707"

[tool.pylint.format]
max-line-length = "88"

[tool.pylint.typecheck]
ignored-classes = ["SQLAlchemy", "scoped_session"]

[tool.pylint.basic]
# f for func, e for error, v for value (in k, v), rv for flask test convention
good-names = ["i", "j", "k", "f", "e", "v", "_", "rv"]

[tool.pylint.variables]
# ignore message as werobot convention
ignored-argument-names = "_.*|^ignored_|^unused_|^message$"
