component: scf
name: pkuphysu-wechat
app: pkuphysu-wechat
stage: ${env:STAGE}
inputs:
  name: ${name}-${stage}
  src:
    src: ./
    exclude:
      - tests/**
      - "*.yml"
      - ".secret*"
  handler: index.main_handler
  region: ap-shanghai
  zone: ap-shanghai-2
  runtime: CustomRuntime
  initTimeout: 10
  timeout: 30
  layers:
    - name: ${output:${stage}:${app}:pkuphysu-wechat-layer.name}
      version: ${output:${stage}:${app}:pkuphysu-wechat-layer.version}
    - name: ${output:${stage}:${app}:pkuphysu-wechat-python.name}
      version: ${output:${stage}:${app}:pkuphysu-wechat-python.version}
  eip: true
  vpcConfig:
    vpcId: ${output:${stage}:${app}:pkuphysu-wechat-vpc.vpcId}
    subnetId: ${output:${stage}:${app}:pkuphysu-wechat-vpc.subnetId}
  environment:
    variables:
      DYNACONF_FLASK__SQLALCHEMY_DATABASE_URI: mysql+pymysql://root:${output:${stage}:${app}:pkuphysu-wechat-db.adminPassword}@${output:${stage}:${app}:pkuphysu-wechat-db.connection.ip}:${output:${stage}:${app}:pkuphysu-wechat-db.connection.port}/pkuphysu?charset=utf8mb4
      ENV_FOR_DYNACONF: ${env:DYNACONF_ENV}
  events:
    - http:
        parameters:
          authType: NONE
          qualifier: $DEFAULT
          netConfig:
            enableIntranet: false
            enableExtranet: true
          corsConfig:
            enable: true
            origins:
              - "*"
            methods:
              - GET
              - POST
              - PUT
              - PATCH
              - DELETE
              - HEAD
              - OPTIONS
    - timer:
        parameters:
          name: health-check
          cronExpression: "0 */10 * * * * *"
          enable: true
