name: Deploy Serverless

on:
  push:
    branches:
      - master
      - dev

jobs:
  deploy:
    name: deploy to serverless
    runs-on: ubuntu-latest
    if: ${{ ! contains(github.event.head_commit.message, '[skip-deploy]') }}
    steps:
      - name: Determine env
        id: env
        run: |
          if [ $GITHUB_REF == 'refs/heads/master' ]; then
            echo '::set-output name=stage::prod'
            echo '::set-output name=dynaconf_env::production'
          else
            echo '::set-output name=stage::dev'
            echo '::set-output name=dynaconf_env::development'
          fi
      - uses: actions/checkout@v6
      - uses: actions/setup-python@v6
        id: python
        with:
          python-version: "3.9"
      - uses: Gr1N/setup-poetry@v9
        with:
          poetry-version: 2.1.4
      - uses: actions/cache@v5
        id: cache
        with:
          path: ~/.cache/pypoetry
          key: ${{ steps.env.outputs.stage }}-poetry-${{ runner.os }}-${{ runner.arch }}-python-${{ steps.python.outputs.python-version }}-poetry-2.1.4-${{ hashFiles('poetry.lock') }}
          restore-keys: ${{ steps.env.outputs.stage }}-poetry-${{ runner.os }}-${{ runner.arch }}-python-${{ steps.python.outputs.python-version }}-poetry-2.1.4-
      - name: Install dependencies
        run: poetry install --only main --no-root --no-interaction
      - name: Get site-packages path
        id: lib-path
        shell: poetry run python {0}
        run: |
          from distutils.sysconfig import get_python_lib
          from pathlib import Path

          lib_parent = Path(get_python_lib()).parent
          print('::set-output name=parent::' + str(lib_parent))
      - name: Determine options
        id: opt
        run: |
          if [ $HIT == 'true' ]; then
            echo '::set-output name=deploy_option::--target src'
          fi
        env:
          HIT: ${{ steps.cache.outputs.cache-hit }}
      - name: Dump secrets
        run: echo $SECRETS | base64 --decode > src/pkuphysu_wechat/config/.secrets.toml
        env:
          SECRETS: ${{ secrets.SECRET_SETTING }}
      - name: Install serverless
        run: npm install -g serverless-cloud-framework@1.3.1

      - name: Debug SCF version
        run: |
          which scf || true
          scf --version || true
          node --version
          npm list -g --depth=0 || true

      - name: Deploy serverless
        shell: bash --noprofile --norc -eo pipefail {0}
        run: |
          # Force deploy to fix permission loss problem
          scf deploy --force ${{ steps.opt.outputs.deploy_option }} --debug
        env:
          STAGE: ${{ steps.env.outputs.stage }}
          LAYER_SRC: ${{ steps.lib-path.outputs.parent }}
          DYNACONF_ENV: ${{ steps.env.outputs.dynaconf_env }}
          SERVERLESS_PLATFORM_VENDOR: tencent
          TENCENT_SECRET_ID: ${{ secrets.TENCENT_SECRET_ID }}
          TENCENT_SECRET_KEY: ${{ secrets.TENCENT_SECRET_KEY }}
